# Generated by Django 3.2.4 on 2022-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_islamicarticle_bcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicarticle',
            name='article_meta',
            field=models.TextField(max_length=500),
        ),
    ]
